---
- import_tasks: "checks.yml"
- import_tasks: "deps_conf.yml"
- import_tasks: master.yml
- import_tasks: worker.yml
# - hosts: all
#   tasks:
#     - name: Install the system dependency
#       import_tasks: deps_conf.yml

#     - name: Init the cluster and setup the master node
#       
#       when: inventory_hostname in groups['k8s-masters']
    
#     - name: Join the nodes
#       import_tasks: worker.yml
