
- name: get join command
  shell: kubeadm token create --print-join-command
  register: join_command_raw
  when: inventory_hostname in groups['k8s-masters']

- name: Creating a file with static network content
  copy:
    dest: "/etc/netplan/60-floating-ip.yaml"
    content: |
      network:
          version: 2
          ethernets:
              eth0:
                  addresses:
                  - {{float_ip_addr}}/32
  when: float_ip_addr is defined and inventory_hostname in groups['k8s-nodes']

- name: Apply netplan
  command: sudo netplan apply
  when: float_ip_addr is defined and inventory_hostname in groups['k8s-nodes']
  
- name: "Add K8S Join command to dummy host"
  add_host:
    name:   "K8S_JOIN_COMMAND"
    token:  "{{ join_command_raw.stdout }}"
  when: inventory_hostname in groups['k8s-masters']

- name: Join node to cluster
  shell: "{{ hostvars['K8S_JOIN_COMMAND']['token'] }} >> node_joined.txt"
  args:
    chdir: $HOME
    creates: node_joined.txt
  when: inventory_hostname in groups['k8s-nodes']