
- name: get join command
  shell: kubeadm token create --print-join-command
  register: join_command_raw
  when: inventory_hostname in groups['k8s-masters']

- name: Debug
  debug:
    msg: "{{ join_command_raw }}"
  # when: inventory_hostname in groups['k8s-nodes']

# - name: join cluster
#   shell: "{{ join_command }} >> node_joined.txt"
#   args:
#     chdir: $HOME
#     creates: node_joined.txt
#   when: inventory_hostname in groups['k8s-nodes']