
- name: get join command
  shell: kubeadm token create --print-join-command
  register: join_command_raw
  when: inventory_hostname in groups['k8s-masters']

- name: Creating a file with static network content
  copy:
    dest: "/etc/network/interfaces.d/60-floating-ip.cfg"
    content: |
      auto eth0:1
      iface eth0:1 inet static
        address {{ float_ip_addr }}
        netmask 32
  when: float_ip_addr is defined
  
- name: "Add K8S Join command to dummy host"
  add_host:
    name:   "K8S_JOIN_COMMAND"
    token:  "{{ join_command_raw.stdout }}"
  when: inventory_hostname in groups['k8s-masters']

- name: Join node to cluster
  shell: "{{ hostvars['K8S_JOIN_COMMAND']['token'] }} >> node_joined.txt"
  args:
    chdir: $HOME
    creates: node_joined.txt
  when: inventory_hostname in groups['k8s-nodes']