- name: get join command
  shell: kubeadm token create --print-join-command
  register: join_command_raw
  when: inventory_hostname in groups['k8s-masters']
 
- name: "Add K8S Join command to dummy host"
  add_host:
    name:   "K8S_JOIN_COMMAND"
    token:  "{{ join_command_raw.stdout }}"
  when: inventory_hostname in groups['k8s-masters']

- name: Join node to cluster
  shell: "{{ hostvars['K8S_JOIN_COMMAND']['token'] }} >> node_joined.txt"
  args:
    chdir: $HOME
    creates: node_joined.txt
  when: inventory_hostname in groups['k8s-workers']


# alias ar='ansible-playbook -i hosts main.yml --extra-vars "hcloud_token=SIDZuxTmWDNFyx9jSiG065WibX3pu74ppBu2LdbGQ5iBt87AQkv0pHICOBVawmLJ hcloud_private_network=k8s-network float_ip_addr=116.203.10.253"'