
- name: get join command
  shell: kubeadm token create --print-join-command
  register: join_command_raw
  when: inventory_hostname in groups['k8s-masters']

- name: set join command
  set_fact:
    join_command: "{{ join_command_raw.stdout_lines[0] }}"
  when: inventory_hostname in groups['k8s-masters']
      


# - name: join cluster
#   shell: "{{ hostvars['k8s-master'].join_command }} >> node_joined.txt"
#   args:
#     chdir: $HOME
#     creates: node_joined.txt
#   when: inventory_hostname  in groups['workers']

- name: Show hostvars
  debug:
    msg: "{{hostvars}}"

- name: Show facts
  debug:
    msg: "{{ join_command }}"